export const SET_LOGIN = "set login";
export const SET_LOGIN_DATA = "set login data";
export const SET_TOKEN = "set token";
export const SET_EMAIL_CHECK = "set email check";
export const SET_REGISTER = "set register";
export const SET_FORGOT_PASSWORD = "set forgot password";
export const SET_CHANGE_PASSWORD = "set change password";
export const SET_FIRST_LOGIN = "set first login";
export const SET_APP_BACKGROUND = "set app background";
