export const SET_SOAL = "set soal";
export const SET_SOAL_URL = "set soal url";
export const SET_QUESTION = "set question";
export const SET_NUMBER = "set number";
export const SET_SAVE_ANSWER = "set save answer";
export const SET_FINAL_ANSWER = "set final answer";
export const SET_SAVE_SCORE = "set save score";
export const SET_JAWABAN = "set jawaban";
export const SET_JAWABAN_NONBLOCKING = "set jawaban non blocking";
