workflows:
    rn-android-playstore:
        name: RN Android Playstore
        instance_type: mac_pro
        environment:
            groups:
                - google_credentials
            android_signing:
                - go_release_keystore
            vars:
                PACKAGE_NAME: "com.goonline.app"
            node: 16.13.0
        cache:
            cache_paths:
                - $CM_BUILD_DIR/node_modules
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: dev-build-android-x
                  include: true
                  source: true
        scripts:
            - name: Install npm dependencies
              script: yarn install
            - name: Build Android Bundle
              working_directory: android
              script: |
                NEW_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME") + 1))
                
                # 42 is required to make build number match current incremented value

                #./gradlew bundleRelease -PversionCode=$NEW_BUILD_NUMBER -PversionName=0.1.$($NEW_BUILD_NUMBER + 42)

                ./gradlew bundleRelease -PversionCode=$NEW_BUILD_NUMBER -PversionName=0.1.111-a
                
        artifacts:
            - android/app/build/**/outputs/bundle/**/*.aab
        publishing:
            email:
                recipients:
                    - leopapilaya@gmail.com
            google_play:
                credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
                track: alpha
